services:
  spark:
    build: .
    container_name: spark-app
    ports:
      - "8080:8080"
      - "8081:8081"
      - "6066:6066"
      - "7077:7077"
    volumes:
      - ./data:/opt/data
      - ./outputs:/opt/outputs
